version: 2

sources:
  - name: scheduling_system
    database: dwh
    schema: staging_scheduling_system
    tables:
      - name: cinema
      - name: movie
      - name: projection
      - name: screen
  
  - name: booking_system
    database: dwh
    schema: staging_booking_system
    tables:
      - name: invoice
      - name: payment
      - name: point_of_sale
      - name: ticket
  - name: ods
    database: dwh
    schema: main_ods
    tables:
      - name: cinema
      - name: screen
      - name: movie
      - name: distribution_company
      - name: projection
      - name: point_of_sale
      - name: person
      - name: role
      - name: ticket
